# render.yaml for FutureWatch application deployment
services:
  # Web service - FastAPI backend
  - type: web
    name: neo-future-dashboard-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt && cd backend && alembic upgrade head
    startCommand: cd backend && python server.py
    healthCheckPath: /health
    envVarGroups:
      - futurewatch-secrets
    plan: standard
    autoDeploy: true
    numInstances: 
      min: 1
      max: 3

  # Worker service - Continuous data ingest
  - type: worker
    name: neo-future-worker
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && python worker/ingest.py
    envVarGroups:
      - futurewatch-secrets
    plan: standard
    autoDeploy: true

# Environment variable groups
envVarGroups:
  - name: futurewatch-secrets
    envVars:
      - key: DATABASE_URL
        value: postgresql://futurewatch_db_user:Nnb7O8ct8H2PR8ruopZqClE6HryQL2Ww@dpg-d000g0a4d50c739pt3l0-a/futurewatch_db
      - key: ENV
        value: production
